GET http://localhost:3000/users

###

GET http://localhost:3000/users/65fff20095a46b95075414f8

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "nanuka@gmail.com",
    "password": "nanuka"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "qwe@qwe.qe",
    "password": "qwe"
}

###

DELETE http://localhost:3000/users/65fff20095a46b95075414f8

###
PATCH http://localhost:3000/users/65fff20095a46b95075414f8
Content-Type: application/json

{
    "email": "updated@hh.com"
}

###

POST http://localhost:3000/favorites
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAwMzBlMmM2MzAzMjViZjkyZTc2ZjAiLCJpYXQiOjE3MTEzNzk2NTUsImV4cCI6MTcxMTM4MzI1NX0.SoU6E2XZTL2Zidf9SOsUqGoLfv3PYxH4c8hA-EPxVNw"

{
    "userId": "660030e2c630325bf92e76f0",
    "id": 1,
    "image": "https://images.squarespace-cdn.com/content/v1/5e10bdc20efb8f0d169f85f9/09943d85-b8c7-4d64-af31-1a27d1b76698/arrow.png",
    "title": "jacket",
    "price": 29,
    "rating": {"rate": 2.5, "count": 21},
    "category": "clothes",
    "description": "cool jacket"
}

###

DELETE http://localhost:3000/favorites/8
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAwMzBlMmM2MzAzMjViZjkyZTc2ZjAiLCJpYXQiOjE3MTEzNzk2NTUsImV4cCI6MTcxMTM4MzI1NX0.SoU6E2XZTL2Zidf9SOsUqGoLfv3PYxH4c8hA-EPxVNw"

{
    "userId": "660030e2c630325bf92e76f0",
    "id": 1
}

###

POST http://localhost:3000/favorites/userfavorites
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjAwMzBlMmM2MzAzMjViZjkyZTc2ZjAiLCJpYXQiOjE3MTEzNzk2NTUsImV4cCI6MTcxMTM4MzI1NX0.SoU6E2XZTL2Zidf9SOsUqGoLfv3PYxH4c8hA-EPxVNw"

{
    "userId": "660017957488e416b3f76895"
}